#!/usr/bin/env python3
"""
Delete comments created by the AI Feature Prioritization Tool

This script finds and deletes comments that were automatically added by the 
template validation agent to avoid spam from incorrect validations.
"""

import os
import requests
import json
import argparse
from datetime import datetime


class AgentCommentCleaner:
    """Clean up comments created by the AI agent"""
    
    def __init__(self, jira_url: str, api_token: str):
        self.jira_url = jira_url.rstrip('/')
        self.api_token = api_token
        self.session = requests.Session()
        self.session.headers.update({
            'Authorization': f'Bearer {api_token}',
            'Content-Type': 'application/json',
            'Accept': 'application/json'
        })
    
    def test_connection(self) -> bool:
        """Test Jira connection"""
        try:
            response = self.session.get(f"{self.jira_url}/rest/api/2/myself", timeout=30)
            if response.status_code == 200:
                user_info = response.json()
                print(f"✅ Connected to Jira as: {user_info.get('displayName', 'Unknown')}")
                return True
            else:
                print(f"❌ Connection failed: HTTP {response.status_code}")
                return False
        except Exception as e:
            print(f"❌ Connection error: {e}")
            return False
    
    def get_rox_features(self) -> list:
        """Get all ROX 4.10 features"""
        try:
            jql = 'project = rox AND type = feature AND "Target Version" = 4.10.0 AND status != Closed'
            
            response = self.session.get(
                f"{self.jira_url}/rest/api/2/search",
                params={
                    'jql': jql,
                    'fields': 'key,summary',
                    'maxResults': 100
                },
                timeout=30
            )
            
            if response.status_code == 200:
                data = response.json()
                features = data.get('issues', [])
                print(f"📋 Found {len(features)} ROX 4.10 features")
                return features
            else:
                print(f"❌ Failed to fetch features: {response.status_code}")
                return []
                
        except Exception as e:
            print(f"❌ Error fetching features: {e}")
            return []
    
    def get_issue_comments(self, issue_key: str) -> list:
        """Get all comments for an issue"""
        try:
            response = self.session.get(
                f"{self.jira_url}/rest/api/2/issue/{issue_key}/comment",
                timeout=30
            )
            
            if response.status_code == 200:
                data = response.json()
                return data.get('comments', [])
            else:
                print(f"   ❌ Failed to get comments for {issue_key}: HTTP {response.status_code}")
                return []
                
        except Exception as e:
            print(f"   ❌ Error getting comments for {issue_key}: {e}")
            return []
    
    def is_agent_comment(self, comment: dict) -> bool:
        """Check if a comment was created by our agent"""
        body = comment.get('body', '')
        
        # Look for agent signatures
        agent_signatures = [
            "Generated by AI Feature Prioritization Tool",
            "Template Compliance Issue",
            "🚨 **Template Compliance Issue**",
            "🧪 **Test Comment from AI Feature Prioritization Tool**"
        ]
        
        return any(signature in body for signature in agent_signatures)
    
    def delete_comment(self, issue_key: str, comment_id: str, dry_run: bool = True) -> bool:
        """Delete a specific comment"""
        if dry_run:
            print(f"   🔄 DRY RUN: Would delete comment {comment_id} from {issue_key}")
            return True
        
        try:
            response = self.session.delete(
                f"{self.jira_url}/rest/api/2/issue/{issue_key}/comment/{comment_id}",
                timeout=30
            )
            
            if response.status_code == 204:
                print(f"   ✅ Deleted comment {comment_id} from {issue_key}")
                return True
            else:
                print(f"   ❌ Failed to delete comment {comment_id} from {issue_key}: HTTP {response.status_code}")
                return False
                
        except Exception as e:
            print(f"   ❌ Error deleting comment {comment_id} from {issue_key}: {e}")
            return False
    
    def clean_comments(self, dry_run: bool = True, specific_issues: list = None) -> dict:
        """Clean agent comments from issues"""
        stats = {
            'issues_checked': 0,
            'comments_found': 0,
            'comments_deleted': 0,
            'errors': 0
        }
        
        print(f"🧹 Cleaning agent comments...")
        print(f"🔧 Mode: {'DRY RUN' if dry_run else 'LIVE'}")
        print("=" * 60)
        
        # Get features to check
        if specific_issues:
            features = [{'key': key, 'fields': {'summary': f'Issue {key}'}} for key in specific_issues]
            print(f"🎯 Checking specific issues: {', '.join(specific_issues)}")
        else:
            features = self.get_rox_features()
        
        if not features:
            print("❌ No features found to check")
            return stats
        
        for feature in features:
            stats['issues_checked'] += 1
            issue_key = feature.get('key', '')
            summary = feature.get('fields', {}).get('summary', 'Unknown')
            
            print(f"\n🔍 Checking {issue_key}: {summary[:50]}...")
            
            # Get comments for this issue
            comments = self.get_issue_comments(issue_key)
            if not comments:
                print(f"   📝 No comments found")
                continue
            
            # Find agent comments
            agent_comments = []
            for comment in comments:
                if self.is_agent_comment(comment):
                    agent_comments.append(comment)
                    stats['comments_found'] += 1
            
            if not agent_comments:
                print(f"   ✅ No agent comments found")
                continue
            
            print(f"   🤖 Found {len(agent_comments)} agent comment(s)")
            
            # Delete agent comments
            for comment in agent_comments:
                comment_id = comment.get('id')
                created = comment.get('created', 'Unknown')
                author = comment.get('author', {}).get('displayName', 'Unknown')
                body_preview = comment.get('body', '')[:100] + "..." if len(comment.get('body', '')) > 100 else comment.get('body', '')
                
                print(f"   📋 Comment {comment_id} by {author} at {created}")
                print(f"      Preview: {body_preview}")
                
                success = self.delete_comment(issue_key, comment_id, dry_run)
                if success and not dry_run:
                    stats['comments_deleted'] += 1
                elif not success:
                    stats['errors'] += 1
        
        print("\n" + "=" * 60)
        print("📈 **Comment Cleanup Summary:**")
        print(f"   Issues checked: {stats['issues_checked']}")
        print(f"   Agent comments found: {stats['comments_found']}")
        
        if dry_run:
            print(f"   Comments that would be deleted: {stats['comments_found']}")
        else:
            print(f"   Comments successfully deleted: {stats['comments_deleted']}")
            print(f"   Errors encountered: {stats['errors']}")
        
        return stats


def main():
    """Main function with command line argument parsing"""
    parser = argparse.ArgumentParser(
        description='Delete comments created by AI Feature Prioritization Tool',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Dry run - see what comments would be deleted
  python3 delete_agent_comments.py --dry-run
  
  # Actually delete the comments
  python3 delete_agent_comments.py --delete
  
  # Delete from specific issues only
  python3 delete_agent_comments.py --delete --issues ROX-30840 ROX-30626
  
  # Check specific issues without deleting
  python3 delete_agent_comments.py --dry-run --issues ROX-30840
        """
    )
    
    parser.add_argument('--jira-url', default='https://issues.redhat.com',
                        help='Jira base URL (default: https://issues.redhat.com)')
    parser.add_argument('--token', default=os.getenv('JIRA_TOKEN', ''),
                        help='Your Jira API token')
    parser.add_argument('--dry-run', action='store_true',
                        help='Show what comments would be deleted without actually deleting them')
    parser.add_argument('--delete', action='store_true',
                        help='Actually delete the agent comments (USE WITH CAUTION)')
    parser.add_argument('--issues', nargs='+',
                        help='Specific issue keys to check (e.g., ROX-30840 ROX-30626)')
    
    args = parser.parse_args()
    
    if not args.token:
        print("❌ Error: Jira API token is required. Set JIRA_TOKEN environment variable or use --token")
        return 1
    
    if not args.dry_run and not args.delete:
        print("❌ Error: Must specify either --dry-run or --delete")
        print("   Use --dry-run first to see what would be deleted")
        return 1
    
    if args.dry_run and args.delete:
        print("❌ Error: Cannot use both --dry-run and --delete")
        return 1
    
    try:
        cleaner = AgentCommentCleaner(
            jira_url=args.jira_url,
            api_token=args.token
        )
        
        # Test connection
        if not cleaner.test_connection():
            return 1
        
        # Clean comments
        dry_run = args.dry_run
        stats = cleaner.clean_comments(dry_run=dry_run, specific_issues=args.issues)
        
        if dry_run and stats['comments_found'] > 0:
            print(f"\n💡 To actually delete {stats['comments_found']} comments, run:")
            if args.issues:
                print(f"   python3 delete_agent_comments.py --delete --issues {' '.join(args.issues)}")
            else:
                print(f"   python3 delete_agent_comments.py --delete")
        
        return 0
        
    except KeyboardInterrupt:
        print("\n🛑 Comment cleanup interrupted by user")
        return 130
    except Exception as e:
        print(f"❌ Error: {e}")
        return 1


if __name__ == "__main__":
    exit(main())
